Add recurring scanning and attestation jobs
RSIDEV-11275

diff --git a/.github/workflows/scan-and-attest-cronjob.yml b/.github/workflows/scan-and-attest-cronjob.yml
--- a/.github/workflows/scan-and-attest-cronjob.yml
+++ b/.github/workflows/scan-and-attest-cronjob.yml
@@ -9,7 +9,7 @@ on:
     - cron: '0 5 * * 1,3' # Runs at 5:00am on Mondays and Wednesdays
 
 jobs:
-  sign-image:
+  resolve-image-tags:
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -25,17 +25,36 @@ jobs:
       - name: Resolve Digests
         id: resolve-digests
         run: |
+          # Force the step to fail if any command fails
+          set -eo pipefail
+    
           FRONTEND_IMAGE_DIGEST=$(docker buildx imagetools inspect ${{ env.FRONTEND_IMAGE_REFERENCE_BY_TAG }} --format "{{json .Manifest.Digest}}" | tr -d '"')
           echo "frontend-image-digest=$FRONTEND_IMAGE_DIGEST" >> $GITHUB_OUTPUT
           
           BACKEND_IMAGE_DIGEST=$(docker buildx imagetools inspect ${{ env.BACKEND_IMAGE_REFERENCE_BY_TAG }} --format "{{json .Manifest.Digest}}" | tr -d '"')
           echo "backend-image-digest=$BACKEND_IMAGE_DIGEST" >> $GITHUB_OUTPUT
-          
-          echo "Frontend digest: $FRONTEND_IMAGE_DIGEST"
-          echo "Backend digest: $BACKEND_IMAGE_DIGEST"
 
-#      - name: Send status to Slack
-#        if: ${{ failure() && github.ref == 'refs/heads/main' }}
-#        uses: digitalservicebund/notify-on-failure-gha@868884a79c05c62cab52b4f79832cc3589c91a12
-#        with:
-#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+      - name: Send status to Slack
+        if: ${{ failure() && github.ref == 'refs/heads/main' }}
+        uses: digitalservicebund/notify-on-failure-gha@868884a79c05c62cab52b4f79832cc3589c91a12
+        with:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+
+  scan-and-attest-frontend-image:
+    needs: resolve-image-tags
+    uses: ./.github/workflows/attest-image.yml
+    secrets: inherit
+    with:
+      image-reference: ${{ inputs.container-registry}}/${{ github.repository }}/frontend@${{ needs.resolve-image-tags.outputs.frontend-image-digest }}
+      app: frontend
+
+  scan-and-attest-backend-image:
+    needs: resolve-image-tags
+    uses: ./.github/workflows/attest-image.yml
+    secrets: inherit
+    with:
+      image-reference: ${{ inputs.container-registry}}/${{ github.repository }}@${{ needs.resolve-image-tags.outputs.backend-image-digest }}
+      app: backend
+      trivy-db-repository: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
+      trivy-java-db-repository: ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db
+      trivy-offile-scan: true
